### ISSUE TITLE
flatpak-builder complaioning of missing "test any"

### ISSUE THREAD

**Issue by rsevero** [TheAppgineer/flatpak-flutter#42]
When "building with flatpak-builder to verify correctness" I am getting:

```
Running: setup-flutter.sh -C .
Building flutter tool...
Resolving dependencies... 
Because flutter_tools depends on test any which doesn't exist (could not find package test in cache), version solving
  failed.

Try again without --offline!
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

After 10 tries it ends with:

`Command 'pub upgrade' still failed after 10 tries, giving up.`

Any idea on how to fix it? Is it something I did wrong on my side?

**Comment by rsevero** [comment]
Downgraded _flutter_ to 3.32.0 and upgraded _test_ to 1.26.2 but the problem remains the same.

_test_ is listed both in _pubspec-sources.json_ and in _package_config.json_.

I am not sure whatelse to check/try.

**Comment by JanKoudijs** [comment]
This is when running `flatpak-builder` on the output files that were generated for `com.example.todo`?

**Comment by rsevero** [comment]
> This is when running `flatpak-builder` on the output files that were generated for `com.example.todo`?

No. This issue is when running with the output files generated for my app.

I can send you the main _yml_ if helpful

**Comment by JanKoudijs** [comment]
> I can send you the main yml if helpful

That could certainly help.

Also send me a link to the app repo and flathub manifest repo, if publicly available.

**Comment by rsevero** [comment]
> > I can send you the main yml if helpful
> 
> That could certainly help.
> 
> Also send me a link to the app repo and flathub manifest repo, if publicly available.

My _flatpak-flutter.yml_ file:

```
id: io.github.rsevero.mapiah
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm19
command: todo
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
cleanup:
  - /var/lib
modules:
  - name: mapiah
    buildsystem: simple
    build-options:
      arch:
        x86_64:
          env:
            BUNDLE_PATH: build/linux/x64/release/bundle
        aarch64:
          env:
            BUNDLE_PATH: build/linux/arm64/release/bundle
      append-path: /usr/lib/sdk/llvm19/bin:/run/build/todo/flutter/bin
      prepend-ld-library-path: /usr/lib/sdk/llvm19/lib
      env:
        PUB_CACHE: /run/build/todo/.pub-cache
    build-commands:
      - flutter build linux --release
      - install -D $BUNDLE_PATH/todo /app/bin/todo
      - cp -r $BUNDLE_PATH/lib /app/bin/lib
      - cp -r $BUNDLE_PATH/data /app/bin/data
    sources:
      - type: git
        url: https://github.com/rsevero/mapiah.git
        commit: 74247501fda3b19b48ba4c9ba026edb0a24531dd
      - type: git
        url: https://github.com/flutter/flutter.git
        tag: 3.32.1
        dest: flutter
```

I haven't published a flathub manifest reop yet.
