### ISSUE TITLE
Failing to build for due to rhttp

### ISSUE THREAD

**Issue by AminBhst** [TheAppgineer/flatpak-flutter#45]
Hey. I know this might be unrelated to flatpak-flutter itself, but I wanted to ask if you know anything about building when using [rhttp](https://pub.dev/packages/rhttp) as a dependency.
This is the error I get when trying to build flatpak:
```
  +63 ms] [17/20] Linking CXX shared library plugins/hotkey_manager_linux/libhotkey_manager_linux_plugin.so
[ +107 ms] [18/20] Linking CXX executable intermediates_do_not_run/brisk
[+22884 ms] [19/20] Generating librhttp.so, _phony_
[        ] FAILED: plugins/rhttp/librhttp.so plugins/rhttp/_phony_ /run/build/Brisk/build/linux/x64/release/plugins/rhttp/librhttp.so
/run/build/Brisk/build/linux/x64/release/plugins/rhttp/_phony_
[        ] cd /run/build/Brisk/build/linux/x64/release/plugins/rhttp && /usr/bin/cmake -E env CARGOKIT_CMAKE=/usr/bin/cmake CARGOKIT_CONFIGURATION=Release
CARGOKIT_MANIFEST_DIR=/run/build/Brisk/linux/flutter/ephemeral/.plugin_symlinks/rhttp/linux/../rust
CARGOKIT_TARGET_TEMP_DIR=/run/build/Brisk/build/linux/x64/release/plugins/rhttp/cargokit_build CARGOKIT_OUTPUT_DIR=/run/build/Brisk/build/linux/x64/release/plugins/rhttp
CARGOKIT_TARGET_PLATFORM=linux-x64 CARGOKIT_TOOL_TEMP_DIR=/run/build/Brisk/build/linux/x64/release/plugins/rhttp/cargokit_build/tool CARGOKIT_ROOT_PROJECT_DIR=/run/build/Brisk/linux
/run/build/Brisk/.pub-cache/hosted/pub.dev/rhttp-0.12.0/cargokit/run_build_tool.sh build-cmake
[        ] Resolving dependencies...
[        ] Got socket error trying to find package collection at https://pub.dev.
[        ] ninja: build stopped: subcommand failed.
[   +4 ms] Building Linux application... (completed in 48.5s)
[        ] "flutter linux" took 49,301ms.
[   +4 ms] Build process failed
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:215:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:96:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:90:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1551:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:494:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:431:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:98:11)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:102:3)
           <asynchronous suspension>


[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1
Error: module Brisk: Child process exited with code 1
FB: Unmounting read-only fs: fusermount3 -uz /home/ryewell/Dev/flatpak-flutter/brisk/.flatpak-builder/rofiles/rofiles-sN0lYS
```

**Comment by JanKoudijs** [comment]
Things get a bit harder when dependencies have Rust (or C/C++) as a subdependency. For the Rust case there is the `--cargo-locks` option, where you can provide paths to `Cargo.lock` files. I had a look at the rhttp repository and saw that it also uses cargokit, for which an extra pubspec has to be specified.

In the failed build you can look up the rhttp dependency in `.flatpak-builder/build/Brisk/.pub-cache/hosted/pub.dev/rhttp`, there you have to lookup the `cargokit` and `rust` subdirectories. Assuming the pub-cache entry replicates the rhttp repository, then the additional options are:

`--extra-pubspecs=.pub-cache/hosted/pub.dev/rhttp/rhttp/cargokit/build_tool --cargo-locks=.pub-cache/hosted/pub.dev/rhttp/rhttp/rust`

**Comment by JanKoudijs** [comment]
Ah, cargokit also requires a patch, name it `run_build_tool.sh.offline.patch` and place it alongside the generated files:

```patch
diff --git a/.pub-cache/hosted/pub.dev/rhttp/rhttp/cargokit/run_build_tool.sh b/.pub-cache/hosted/pub.dev/rhttp/rhttp/cargokit/run_build_tool.sh
index 0e2c973..200b520 100755
--- a/.pub-cache/hosted/pub.dev/rhttp/rhttp/cargokit/run_build_tool.sh
+++ b/.pub-cache/hosted/pub.dev/rhttp/rhttp/cargokit/run_build_tool.sh
@@ -66,7 +66,7 @@ fi

 # Run pub get if needed.
 if [ ! -f "$PACKAGE_HASH_FILE" ]; then
-    "$DART" pub get --no-precompile
+    "$DART" pub get --no-precompile --offline
     "$DART" compile kernel bin/build_tool_runner.dart
     echo "$PACKAGE_HASH" > "$PACKAGE_HASH_FILE"
 fi
@@ -79,7 +79,7 @@ exit_code=$?

 # 253 means invalid snapshot version.
 if [ $exit_code == 253 ]; then
-  "$DART" pub get --no-precompile
+  "$DART" pub get --no-precompile --offline
   "$DART" compile kernel bin/build_tool_runner.dart
   "$DART" bin/build_tool_runner.dill "$@"
   exit_code=$?
```

**Comment by AminBhst** [comment]
Alright thanks that's fixed now but we're getting new errors each time xD
This time:
```
[        ] 11 packages have newer versions incompatible with dependency constraints.
[        ] Try `dart pub outdated` for more information.
[        ] Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
[        ] SEVERE: ================================================================================
[        ] SEVERE: Cargokit BuildTool failed with error:
[        ] SEVERE: --------------------------------------------------------------------------------
[        ] SEVERE:
[        ] SEVERE: rustup not found in PATH.
[        ] SEVERE:
[        ] SEVERE: Maybe you need to install Rust? It only takes a minute:
[        ] SEVERE:
[        ] SEVERE: $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
[        ] SEVERE:
[        ] SEVERE: ================================================================================
```
I tried adding rustup using `append-path: /usr/lib/sdk/llvm19/bin:/var/lib/flutter/bin:/var/lib/rustup/bin` but it resulted in an error saying that it couldn't download which makes sense because it's in a compile stage and it would run offline.

**Comment by AminBhst** [comment]
This is the flatpak-flutter if that helps:
```yml
id: io.github.BrisklyDev.Brisk
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
- org.freedesktop.Sdk.Extension.llvm19
- org.freedesktop.Sdk.Extension.rust-stable
command: brisk
finish-args:
- --socket=fallback-x11
- --socket=wayland
- --share=network
- --share=ipc
- --device=dri
- --filesystem=xdg-download
- --talk-name=org.freedesktop.Notifications
- --talk-name=org.kde.StatusNotifierWatcher
cleanup:
- /var/lib
modules:
- shared-modules/libayatana-appindicator/libayatana-appindicator-gtk3.json
- name: keybinder
  buildsystem: autotools
  sources:
  - type: archive
    url: https://github.com/kupferlauncher/keybinder/releases/download/keybinder-3.0-v0.3.2/keybinder-3.0-0.3.2.tar.gz
    sha256: e6e3de4e1f3b201814a956ab8f16dfc8a262db1937ff1eee4d855365398c6020
- name: Brisk
  buildsystem: simple
  build-options:
    arch:
      x86_64:
        env:
          BUNDLE_PATH: build/linux/x64/release/bundle
      aarch64:
        env:
          BUNDLE_PATH: build/linux/arm64/release/bundle
    append-path: /usr/lib/sdk/llvm19/bin:/run/build/todo/flutter/bin
    prepend-ld-library-path: /usr/lib/sdk/llvm19/lib
    env:
      PUB_CACHE: /run/build/Brisk/.pub-cache
  build-commands:
  - setup-flutter.sh -C .
  - flutter build linux --release --verbose
  - install -Dm644 .github/io.github.BrisklyDev.Brisk.appdata.xml /app/share/appdata/io.github.BrisklyDev.Brisk.appdata.xml
  - install -D $BUNDLE_PATH/brisk /app/bin/brisk
  - cp -r $BUNDLE_PATH/lib /app/bin/lib
  - cp -r $BUNDLE_PATH/data /app/bin/data
  - install -Dm644 assets/icons/logo-128.png /app/share/icons/hicolor/128x128/apps/io.github.BrisklyDev.Brisk.png
  - desktop-file-edit linux/brisk.desktop --set-icon=io.github.BrisklyDev.Brisk
  - install -Dm644 linux/brisk.desktop /app/share/applications/io.github.BrisklyDev.Brisk.desktop
  sources:
  - type: git
    url: https://github.com/AminBhst/brisk-dev.git
    tag: v2.3.1
    commit: 97aabfb4fad45238ce84a37a48cb641736f93e4b
  - type: git
    url: https://github.com/flutter/flutter.git
    tag: 3.32.0
    dest: flutter

```

**Comment by AminBhst** [comment]
This is flatpak-flutter.yml if that helps:
```yml
id: io.github.BrisklyDev.Brisk
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
- org.freedesktop.Sdk.Extension.llvm19
- org.freedesktop.Sdk.Extension.rust-stable
command: brisk
finish-args:
- --socket=fallback-x11
- --socket=wayland
- --share=network
- --share=ipc
- --device=dri
- --filesystem=xdg-download
- --talk-name=org.freedesktop.Notifications
- --talk-name=org.kde.StatusNotifierWatcher
cleanup:
- /var/lib
modules:
- shared-modules/libayatana-appindicator/libayatana-appindicator-gtk3.json
- name: keybinder
  buildsystem: autotools
  sources:
  - type: archive
    url: https://github.com/kupferlauncher/keybinder/releases/download/keybinder-3.0-v0.3.2/keybinder-3.0-0.3.2.tar.gz
    sha256: e6e3de4e1f3b201814a956ab8f16dfc8a262db1937ff1eee4d855365398c6020
- name: Brisk
  buildsystem: simple
  build-options:
    arch:
      x86_64:
        env:
          BUNDLE_PATH: build/linux/x64/release/bundle
      aarch64:
        env:
          BUNDLE_PATH: build/linux/arm64/release/bundle
    append-path: /usr/lib/sdk/llvm19/bin:/run/build/todo/flutter/bin
    prepend-ld-library-path: /usr/lib/sdk/llvm19/lib
    env:
      PUB_CACHE: /run/build/Brisk/.pub-cache
  build-commands:
  - setup-flutter.sh -C .
  - flutter build linux --release --verbose
  - install -Dm644 .github/io.github.BrisklyDev.Brisk.appdata.xml /app/share/appdata/io.github.BrisklyDev.Brisk.appdata.xml
  - install -D $BUNDLE_PATH/brisk /app/bin/brisk
  - cp -r $BUNDLE_PATH/lib /app/bin/lib
  - cp -r $BUNDLE_PATH/data /app/bin/data
  - install -Dm644 assets/icons/logo-128.png /app/share/icons/hicolor/128x128/apps/io.github.BrisklyDev.Brisk.png
  - desktop-file-edit linux/brisk.desktop --set-icon=io.github.BrisklyDev.Brisk
  - install -Dm644 linux/brisk.desktop /app/share/applications/io.github.BrisklyDev.Brisk.desktop
  sources:
  - type: git
    url: https://github.com/AminBhst/brisk-dev.git
    tag: v2.3.1
    commit: 97aabfb4fad45238ce84a37a48cb641736f93e4b
  - type: git
    url: https://github.com/flutter/flutter.git
    tag: 3.32.0
    dest: flutter
```

**Comment by JanKoudijs** [comment]
The main thing missing are the environment variables, to make sure the downloaded Rust dependencies can be found during build. flatpak-flutter doesn't inject these variables (yet).

This is what gave me a successful build:

    flatpak-flutter --extra-pubspecs=.pub-cache/hosted/pub.dev/rhttp-0.12.0/cargokit/build_tool --cargo-locks=.pub-cache/hosted/pub.dev/rhttp-0.12.0/rust flatpak-flutter.yml

```yaml
id: io.github.BrisklyDev.Brisk
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
- org.freedesktop.Sdk.Extension.llvm19
command: brisk
finish-args:
- --socket=fallback-x11
- --socket=wayland
- --share=network
- --share=ipc
- --device=dri
- --filesystem=xdg-download
- --talk-name=org.freedesktop.Notifications
- --talk-name=org.kde.StatusNotifierWatcher
cleanup:
- /var/lib
modules:
- shared-modules/libayatana-appindicator/libayatana-appindicator-gtk3.json
- name: keybinder
  buildsystem: autotools
  sources:
  - type: archive
    url: https://github.com/kupferlauncher/keybinder/releases/download/keybinder-3.0-v0.3.2/keybinder-3.0-0.3.2.tar.gz
    sha256: e6e3de4e1f3b201814a956ab8f16dfc8a262db1937ff1eee4d855365398c6020
- name: Brisk
  buildsystem: simple
  build-options:
    arch:
      x86_64:
        env:
          BUNDLE_PATH: build/linux/x64/release/bundle
      aarch64:
        env:
          BUNDLE_PATH: build/linux/arm64/release/bundle
    append-path: /usr/lib/sdk/llvm19/bin:/var/lib/rustup/bin:/run/build/todo/flutter/bin
    prepend-ld-library-path: /usr/lib/sdk/llvm19/lib
    env:
      CARGO_HOME: /run/build/Brisk/cargo
      RUSTUP_HOME: /var/lib/rustup
      PUB_CACHE: /run/build/Brisk/.pub-cache
  build-commands:
  - flutter build linux --release --verbose
  - install -Dm644 .github/io.github.BrisklyDev.Brisk.appdata.xml /app/share/appdata/io.github.BrisklyDev.Brisk.appdata.xml
  - install -D $BUNDLE_PATH/brisk /app/bin/brisk
  - cp -r $BUNDLE_PATH/lib /app/bin/lib
  - cp -r $BUNDLE_PATH/data /app/bin/data
  - install -Dm644 assets/icons/logo-128.png /app/share/icons/hicolor/128x128/apps/io.github.BrisklyDev.Brisk.png
  - desktop-file-edit linux/brisk.desktop --set-icon=io.github.BrisklyDev.Brisk
  - install -Dm644 linux/brisk.desktop /app/share/applications/io.github.BrisklyDev.Brisk.desktop
  sources:
  - type: git
    url: https://github.com/AminBhst/brisk-dev.git
    tag: v2.3.1
    commit: 97aabfb4fad45238ce84a37a48cb641736f93e4b
  - type: git
    url: https://github.com/flutter/flutter.git
    tag: 3.32.0
    dest: flutter
```

```patch
diff --git a/.pub-cache/hosted/pub.dev/rhttp-0.12.0/cargokit/run_build_tool.sh b/.pub-cache/hosted/pub.dev/rhttp-0.12.0/cargokit/run_build_tool.sh
index 0e2c973..200b520 100755
--- a/.pub-cache/hosted/pub.dev/rhttp-0.12.0/cargokit/run_build_tool.sh
+++ b/.pub-cache/hosted/pub.dev/rhttp-0.12.0/cargokit/run_build_tool.sh
@@ -66,7 +66,7 @@ fi

 # Run pub get if needed.
 if [ ! -f "$PACKAGE_HASH_FILE" ]; then
-    "$DART" pub get --no-precompile
+    "$DART" pub get --no-precompile --offline
     "$DART" compile kernel bin/build_tool_runner.dart
     echo "$PACKAGE_HASH" > "$PACKAGE_HASH_FILE"
 fi
@@ -79,7 +79,7 @@ exit_code=$?

 # 253 means invalid snapshot version.
 if [ $exit_code == 253 ]; then
-  "$DART" pub get --no-precompile
+  "$DART" pub get --no-precompile --offline
   "$DART" compile kernel bin/build_tool_runner.dart
   "$DART" bin/build_tool_runner.dill "$@"
   exit_code=$?
```
