### ISSUE TITLE
Build successful, but "Command not found" after "Finishing the app"

### ISSUE THREAD

**Issue by PureTryOut** [TheAppgineer/flatpak-flutter#7]
I'm trying to package [an application](https://github.com/nucleus-ffm/foss_warn/pull/180) using this, thanks for the project!
I got both the online and offline build fully working with Flutter 3.29.0 but it fails at the very end with `Error: Command 'foss_warn' not found`. I find this strange however because as far as I can see the executable _is_ installed.

The offline manifest atm:

```yml
id: "de.nucleus.foss_warn"
runtime: "org.freedesktop.Platform"
runtime-version: "24.08"
sdk: "org.freedesktop.Sdk"
command: "foss_warn"
finish-args:
  - "--share=ipc"
  - "--socket=fallback-x11"
  - "--socket=wayland"
  - "--device=dri"
  - "--share=network"
cleanup-commands:
  - "rm -r /var/lib/*"
modules:
  - name: "foss_warn"
    buildsystem: "simple"
    build-options:
      arch:
        x86_64:
          env:
            BUNDLE_PATH: "/run/build/foss_warn/build/linux/x64/release/bundle"
        aarch64:
          env:
            BUNDLE_PATH: "/run/build/foss_warn/build/linux/arm64/release/bundle"
      append-path: "/usr/lib/sdk/llvm19/bin:/var/lib/flutter/bin"
      prepend-ld-library-path: "/usr/lib/sdk/llvm19/lib"
      env:
        PUB_CACHE: "/run/build/foss_warn/.pub-cache"
    build-commands:
      - "mkdir -p build/native_assets/linux"
      - "setup-flutter.sh"
      - "flutter gen-l10n"
      - "flutter build linux --release"
      - "install -D $BUNDLE_PATH/foss_warn /app/bin/foss_warn"
      - "cp -r $BUNDLE_PATH/lib /app/bin/lib"
      - "cp -r $BUNDLE_PATH/data /app/bin/data"
    sources:
      - type: "git"
        url: "https://github.com/PureTryOut/foss_warn"
        branch: "feat/linux-support"
      - type: "file"
        path: "package_config.json"
        dest: "flutter/packages/flutter_tools/.dart_tool"
      - "pubspec-sources-flutter.json"
      - "pubspec-sources-foss_warn.json"
    modules:
      - "flutter-sdk-3.29.0.json"
```

The last part of the build log:

```
Building Linux application...                                           
✓ Built build/linux/x64/release/bundle/foss_warn
Running: install -D $BUNDLE_PATH/foss_warn /app/bin/foss_warn
Running: cp -r $BUNDLE_PATH/lib /app/bin/lib
Running: cp -r $BUNDLE_PATH/data /app/bin/data
Committing stage build-foss_warn to cache
Cleaning up
Committing stage cleanup to cache
Finishing app
Error: Command 'foss_warn' not found

Offline build failed, please verify output for details
```
